### ISSUE TITLE
Build the index page

### ISSUE THREAD

**Issue by harrisonkimdev** [harrisonkimdev/Dashboard#11]
## Tasks
- Fetch sets of tasks.
  - Utilize pagination (lazy loading) for earlier days.
- A set of tasks (6) for a day will be divided into three differnet sections: morning, afternoon, evening.
- Provide users an option to mark/unmark tasks to indicate whether it's completed task or not.
- Show users the keyword and description for each task.

## From Server 
- [x] Sets of tasks associated with the currently signed-in user.

## Frontend
- [x] Use a carousel as a wrapper for a set of tasks to implement pagination.
- [x] List tasks with a checkbox on the left side of the task keyword and description. (all in a single line)
  - [x] If a task is completed, the checkbox associated with it should be checked and the description should have line-through on it.
- [x] The description of each task should be clickable as a link and it would lead users to the Show page for an associated task.

## To Server
- [x] If a user checks out a checkbox, update the database.

## Backend
- [x] Build Index and Update in TaskController

## API References
- GET /blocksix
- PATCH /blocksix/{id}

## Assets
- N/A

## External Libraries
- N/A

## Security
- Authorization required

**Comment by harrisonkimdev** [comment]
Decided to remove modals for quick-edit. Planning to create a dedicated page for edit. Will keep working on the comment modal.
