### ISSUE TITLE
The better Notes

### ISSUE THREAD

**Issue by harrisonkimdev** [harrisonkimdev/Dashboard#18]
## Brief
- Based on Notes I built last year, I'm planning to build A Better Notes with some additional features that I wanted to add on.

## Tasks
- [x] https://github.com/hhkimmm9/Dashboard/issues/20
- [x] https://github.com/hhkimmm9/Dashboard/issues/21
- [x] https://github.com/hhkimmm9/Dashboard/issues/23
- [x] https://github.com/hhkimmm9/Dashboard/issues/25
