### ISSUE TITLE
Build Notes reader & writer

### ISSUE THREAD

**Issue by harrisonkimdev** [harrisonkimdev/Dashboard#23]
## Tasks
- [x] Build the writer section for Notes with Quill editor
  - https://vueup.github.io/vue-quill/
- [x] Create a model, a migration, and a controller for this work in the backend.
- [x] Create Create, Show, and Edit pages
- [x] Implement CRUD opertaions
