### ISSUE TITLE
Build two sections for the list of folders and notes

### ISSUE THREAD

**Issue by harrisonkimdev** [harrisonkimdev/Dashboard#25]
## Tasks
- [x] display a list of notes & folders coming from the server
- [x] Update and Delete a folder
- [x] Update and Delete a note
- [x] Open a folder
- [x] Open a note
