### ISSUE TITLE
Build the create page

### ISSUE THREAD

**Issue by harrisonkimdev** [harrisonkimdev/Dashboard#6]
## Tasks
- Take inputs for a keyword and a description from a user to make a list of tasks for today.
- Provide users a link to let them allow to purchase BlockSix

## From Server 
- N/A

## Frontend
- [x] Build a form for tasks of the day.
  - [x] 2 blocks for each section; morning, afternoon, and evening.
  - [x] Each input field for a task should have two separate input fields for a keyword and a description.
- [x] Add some nice styling to the form.
- [ ] Provide users an option to change the type of task; Core/Rest

## To Server
- [x] A form for tasks.

## Backend
- [x] Validate the input.
- [x] Store them into the database.
- [x] Redirect users to the Dashboard page

## API References
- POST /task

## Assets
- [x] BlockSix book cover image

## External Libraries
- Tippy.js

## Security
- Authorization required
