### ISSUE TITLE
Build the show page

### ISSUE THREAD

**Issue by harrisonkimdev** [harrisonkimdev/Dashboard#9]
## Tasks
- Show users the following:
  - A keyword and a description of the task associated with the ID from the URL.
  - Subtasks associated with the task.
  - Comments associated with the task.
- Provide users the ability to edit the keyword and the description.
- Provide users the ability to add and edit a subtask.
- Provide users the ability to add/edit/delete a comment.

## From Server
- [x] A task associated the ID from the URL
- [x] Subtasks associated with the task
- [x] Comments associated with the task

## Frontend
- [x] A checkbox, keyword and description in a single line.
- [x] A section for subtasks with a scroll bar.
- [x] A section for comments with a scroll bar.

## To Server
- [x] The status of currently opened task is updated: completed <-> incompleted.
- [x] #28
- [x] Create/edit/delete a subtask.
- [x] Create/edit/delete a new comment

## Backend
- [x] Update the status of a task; completed/incompleted.
- [x] Validate and update the keyword and the description of a task.
- [x] Validate and create/update subtasks.
- [x] Validate and create/update comments.
- [x] Delete a comment.

## API References
- PATCH /task/{id} for is_completed and keyword & description
- POST /task with parent_id
- POST /comment
- PATCH /comment/{id}
- DELETE /comment/{id}

## Assets
- N/A

## External Libraries
- N/A

## Security
- Authorization required.

**Comment by hhkimmm9** [comment]
It urns out I can't use show() for this work. A group of tasks for a day have 6 different IDs and show() requires only one id to fetch the data. Decided to merge it with the index page.
